# Generated by Django 6.0.7 on 2026-07-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_1', models.CharField(blank=True, max_length=255, null=True)),
                ('test_2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ae_test',
            },
        ),
    ]
