# Generated by Django 6.0.7 on 2026-08-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('store_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('store_password', models.CharField(blank=True, max_length=255, null=True)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('store_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('store_services', models.JSONField(blank=True, max_length=255, null=True)),
                ('store_langauges', models.JSONField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ae_store',
            },
        ),
    ]
