# Generated by Django 6.0.7 on 2026-08-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='test_id',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='test_2',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='test_1',
            new_name='store_password',
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_langauges',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_services',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='store',
            table='ae_store',
        ),
    ]
