BAD_REQUEST = "some required field missing"
STORE_EMAIL_ALREADY_EXISTS = "store email already exists"
STORE_REGISTERED_SUCCESSFULLY = "store registered successfully"
SERIALIZER_IS_NOT_VALID = "serializer is not valid"
TOKEN_IS_EXPIRED = "token is expired"
USER_NOT_FOUND = "user not found"
USER_NOT_FOUND = "user not found"

# password validation
PASSWORD_LENGTH_SHOULD_BE_BETWEEN_8_TO_20 = "Your password length should be between 8 to 20."
PASSWORD_MUST_HAVE_ONE_NUMBER = "Your password must have at least 1 number"
PASSWORD_MUST_HAVE_ONE_SMALLERCASE_LETTER = "Your password must have at least 1 uppercase letter."
PASSWORD_MUST_HAVE_ONE_SPECIAL_CHARACTER = "Your password must have at least 1 special character ($, #, @, !, *)"
PASSWORD_MUST_HAVE_ONE_UPPERCASE_LETTER = "Your password must have at least 1 uppercase letter."
PASSWORD_UPDATED_SUCCESSFULLY = "Password updated successfully"
INCORRECT_PASSWORD = "incorrect password"
